baseURL: "https://keen-bienenstitch-e0d235.netlify.app" #http://example.org/
languageCode: en-us
title: My First Hugo Site
theme: starter-hugo-academic # starter-hugo-research-group # hugo-PaperMod # hugo-arogya-theme #

############################
## MODULES
############################
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5


params:
  homeInfoParams: 
    Title: "Hello stanger"
    Content: Welcome to my blog
  socialIcons: 
    - name: facebook
      url: 'https://facebook.com/'
    - name: google
      url: 'https://google.com/'


  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: academic  
      name: Academic
      parent: contact
      url: contact/academic/
      weight: 1  
    - identifier: something
      name: Something
      parent: contact
      url: contact/something/
      weight: 2
